backend:
  name: github
  repo: jfserviciosweb10/practica-tienda-digital
  branch: main
  base_url: https://jf-decap-oauth.jfserviciosweb.workers.dev

media_folder: "img/uploads"
public_folder: "img/uploads"

collections:
  - name: "posts"
    label: "Artículos del Blog"
    folder: "blog/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Descripción corta", name: "description", widget: "string" }
      - { label: "Imagen de portada", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "productos"
    label: "Productos (Tienda Digital)"
    files:
      - file: "_data/productos.yml"
        label: "Mis productos"
        name: "productos"
        fields:
          - label: "Productos"
            name: "productos"
            widget: "list"
            summary: "{{fields.nombre}} — {{fields.precio}}"
            fields:
              - { label: "Nombre del producto", name: "nombre", widget: "string" }
              - { label: "Precio", name: "precio", widget: "string", hint: "Ej: $15.000" }
              - { label: "Foto", name: "imagen", widget: "image" }
              - { label: "Descripción (opcional)", name: "descripcion", widget: "text", required: false }
